### ISSUE TITLE
Exceptions thrown from the CLI cause CLI to be stuck

### ISSUE THREAD

**Issue by oritstone** [openscore/score-language#142]
When a RuntimeException is thrown from running a task in loop in the CLI, it is no longer printed to the CLI, only to the log, and the score worker starts doing recovery.
The CLI is stuck from that moment in the middle of the execution, and you need to close the cmd.

Exception in log:

2015-03-05 15:00:30:835 1899190 [WorkerExecutionThread-12_101600085] ERROR org.openscore.lang.runtime.steps.ExecutableSteps  - There was an error running the start executable execution step of: 'ping'. Error is: Input with name: 'text' is Required, but value is empty
2015-03-05 15:00:30:835 1899190 [WorkerExecutionThread-12_101600085] ERROR org.openscore.worker.execution.reflection.ReflectionAdapterImpl  - Failed to run the action! Class: org.openscore.lang.runtime.steps.ExecutableSteps, method: startExecutable, reason: Error running: 'ping': Input with name: 'text' is Required, but value is empty
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openscore.worker.execution.reflection.ReflectionAdapterImpl.executeControlAction(ReflectionAdapterImpl.java:62)
	at org.openscore.worker.execution.services.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:316)
	at org.openscore.worker.execution.services.ExecutionServiceImpl.execute(ExecutionServiceImpl.java:78)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.executeRegularStep(SimpleExecutionRunnable.java:147)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.run(SimpleExecutionRunnable.java:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.openscore.worker.management.services.WorkerThreadFactory$1.run(WorkerThreadFactory.java:33)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error running: 'ping': Input with name: 'text' is Required, but value is empty
	at org.openscore.lang.runtime.steps.ExecutableSteps.startExecutable(ExecutableSteps.java:90)
	... 14 more
Caused by: java.lang.RuntimeException: Input with name: 'text' is Required, but value is empty
	at org.openscore.lang.runtime.bindings.InputsBinding.bindInput(InputsBinding.java:58)
	at org.openscore.lang.runtime.bindings.InputsBinding.bindInputs(InputsBinding.java:41)
	at org.openscore.lang.runtime.steps.ExecutableSteps.startExecutable(ExecutableSteps.java:67)
	... 14 more
2015-03-05 15:00:30:836 1899191 [WorkerExecutionThread-12_101600085] ERROR org.openscore.worker.execution.services.ExecutionServiceImpl  - Error occurred during operation execution.  Execution id: 101600085
org.openscore.exceptions.FlowExecutionException: Error running: 'ping': Input with name: 'text' is Required, but value is empty
	at org.openscore.worker.execution.reflection.ReflectionAdapterImpl.executeControlAction(ReflectionAdapterImpl.java:73)
	at org.openscore.worker.execution.services.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:316)
	at org.openscore.worker.execution.services.ExecutionServiceImpl.execute(ExecutionServiceImpl.java:78)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.executeRegularStep(SimpleExecutionRunnable.java:147)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.run(SimpleExecutionRunnable.java:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.openscore.worker.management.services.WorkerThreadFactory$1.run(WorkerThreadFactory.java:33)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openscore.worker.execution.reflection.ReflectionAdapterImpl.executeControlAction(ReflectionAdapterImpl.java:62)
	... 10 more
Caused by: java.lang.RuntimeException: Error running: 'ping': Input with name: 'text' is Required, but value is empty
	at org.openscore.lang.runtime.steps.ExecutableSteps.startExecutable(ExecutableSteps.java:90)
	... 14 more
Caused by: java.lang.RuntimeException: Input with name: 'text' is Required, but value is empty
	at org.openscore.lang.runtime.bindings.InputsBinding.bindInput(InputsBinding.java:58)
	at org.openscore.lang.runtime.bindings.InputsBinding.bindInputs(InputsBinding.java:41)
	at org.openscore.lang.runtime.steps.ExecutableSteps.startExecutable(ExecutableSteps.java:67)
	... 14 more
2015-03-05 15:00:30:837 1899192 [WorkerExecutionThread-12_101600085] INFO  org.openscore.lang.cli.SlangCLI  - Event received: SLANG_EXECUTION_EXCEPTION Data is: {EXECUTIONID=101600085, DESCRIPTION=Error detected during step, PATH=0/1/0, TIMESTAMP=Thu Mar 05 15:00:30 IST 2015, TYPE=SLANG_EXECUTION_EXCEPTION, EXCEPTION=Error running: 'ping': Input with name: 'text' is Required, but value is empty}
2015-03-05 15:00:30:846 1899201 [WorkerExecutionThread-12_101600085] ERROR org.openscore.worker.management.services.SimpleExecutionRunnable  - Error during execution!!!
java.lang.RuntimeException: Failed to serialize execution plan. Error: 
	at org.openscore.engine.queue.entities.ExecutionMessageConverter.objToBytes(ExecutionMessageConverter.java:72)
	at org.openscore.engine.queue.entities.ExecutionMessageConverter.createPayload(ExecutionMessageConverter.java:36)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.createTerminatedExecutionMessage(SimpleExecutionRunnable.java:323)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.isExecutionTerminating(SimpleExecutionRunnable.java:393)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.shouldStop(SimpleExecutionRunnable.java:163)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.executeRegularStep(SimpleExecutionRunnable.java:149)
	at org.openscore.worker.management.services.SimpleExecutionRunnable.run(SimpleExecutionRunnable.java:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.openscore.worker.management.services.WorkerThreadFactory$1.run(WorkerThreadFactory.java:33)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.NotSerializableException: java.util.ArrayList$Itr
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at java.util.HashMap.writeObject(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeArray(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.access$300(Unknown Source)
	at java.io.ObjectOutputStream$PutFieldImpl.writeFields(Unknown Source)
	at java.io.ObjectOutputStream.writeFields(Unknown Source)
	at java.util.Vector.writeObject(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at java.util.HashMap.writeObject(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at org.openscore.engine.queue.entities.ExecutionMessageConverter.objToBytes(ExecutionMessageConverter.java:66)
	... 12 more
2015-03-05 15:00:30:926 1899281 [scoreWorkerScheduler-4] ERROR org.openscore.worker.management.services.RetryTemplate  - Try #1 failed on: 
java.lang.NullPointerException
	at org.openscore.engine.queue.entities.ExecutionMessageConverter.extractExecution(ExecutionMessageConverter.java:32)
	at org.openscore.engine.queue.services.QueueListenerImpl.extractExecution(QueueListenerImpl.java:136)
	at org.openscore.engine.queue.services.QueueListenerImpl.deleteExecutionStateObjects(QueueListenerImpl.java:194)
	at org.openscore.engine.queue.services.QueueListenerImpl.onFailed(QueueListenerImpl.java:145)
	at org.openscore.engine.queue.services.ExecutionQueueServiceImpl.enqueue(ExecutionQueueServiceImpl.java:102)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy74.enqueue(Unknown Source)
	at org.openscore.engine.queue.services.QueueDispatcherServiceImpl.dispatch(QueueDispatcherServiceImpl.java:50)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy88.dispatch(Unknown Source)
	at org.openscore.orchestrator.services.OrchestratorDispatcherServiceImpl$1.handle(OrchestratorDispatcherServiceImpl.java:86)
	at org.openscore.orchestrator.services.OrchestratorDispatcherServiceImpl.dispatch(OrchestratorDispatcherServiceImpl.java:109)
	at org.openscore.orchestrator.services.OrchestratorDispatcherServiceImpl.dispatch(OrchestratorDispatcherServiceImpl.java:82)
	at org.openscore.orchestrator.services.OrchestratorDispatcherServiceImpl.dispatch(OrchestratorDispatcherServiceImpl.java:70)
	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy95.dispatch(Unknown Source)
	at org.openscore.worker.management.services.OutboundBufferImpl$1.tryOnce(OutboundBufferImpl.java:187)
	at org.openscore.worker.management.services.RetryTemplate.retry(RetryTemplate.java:36)
	at org.openscore.worker.management.services.OutboundBufferImpl.drainBulk(OutboundBufferImpl.java:182)
	at org.openscore.worker.management.services.OutboundBufferImpl.drainInternal(OutboundBufferImpl.java:155)
	at org.openscore.worker.management.services.OutboundBufferImpl.drain(OutboundBufferImpl.java:124)
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by meirwah** [comment]
@tudorlesan is this related to the outputs change you made with the outputs???

**Comment by meirwah** [comment]
@tudorlesan please look into this... maybe also revert locally the outputs commit to see if this is related..,

**Comment by oritstone** [comment]
Flow example:
```Yaml
namespace: loops
imports:
  ops: loops
flow:
  name: bug_flow
  inputs:
    - host_list: [1,2,3]
  workflow:
    - ping_host:
        loop:
          for: host in host_list
          do:
            ops.ping:
              - host
```

Operation:
```Yaml
namespace: loops
operation:
  name: ping
  inputs:
     - host
  action:
    python_script: |
        print "ping " + host
```

**Comment by orius123** [comment]
@oritstone works for me, I think it happened because score failed to serialize the loop iterator.
it is fixed now so I guess that is it..

**Comment by meirwah** [comment]
why is this "ready for merge" ? this is an issue .. not PR...

**Comment by orius123** [comment]
dragged with waffle. I guess..

**Comment by oritstone** [comment]
I still need to test that is doesn't not reproduce on Windows, so let's leave it here

**Comment by oritstone** [comment]
Works now. Was probably fixed with the Seialization issue fix
